### ISSUE TITLE
Refresh Button doesn't work anymore 

### ISSUE THREAD

**Issue by aalsharef** [mlava/numbered-list#1]
Thanks for creating the great feature. The "Refresh" button doesn't work anymore.

Thanks!

**Comment by mlava** [comment]
Thanks @aalsharef I'm working on a fix

**Comment by mlava** [comment]
@aalsharef I have been able to create a fix for this issue. It does require the use of a SmartBlock, so you would have to have that extension installed as well.

If you don't have SmartBlocks, you can update your numbering via the Command Palette command, but there won't be a button to click. I hope this will be ok, but there's no other simple way to achieve this.
