### ISSUE TITLE
Undo?

### ISSUE THREAD

**Issue by LuciferIsSatan** [mlava/numbered-list#2]
Is there a way to start over and take all the numbers off? I want to start fresh and I had a List of 1000 Bullets turn into numbers. I can't figure out how to undo it?

**Comment by mlava** [comment]
I am uploading a new version soon that implements a Remove function for both Command Palette and SmartBlocks. Good idea!

**Comment by mlava** [comment]
https://github.com/Roam-Research/roam-depot/pull/789

**Comment by mlava** [comment]
@LuciferIsSatan this fix is now live

**Comment by LuciferIsSatan** [comment]
> @LuciferIsSatan this fix is now live

Thank you! Much appreciated.
